name: check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true
  TF_STATE_BUCKET: "env-tfbackend-oss-backend"
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1.3.2 # https://github.com/hashicorp/setup-terraform/releases
        with:
          terraform_version: 1.1.4 # https://github.com/hashicorp/terraform/releases
          terraform_wrapper: false
      - name: prep
        shell: bash
        run: |
          echo "TF_VAR_git=$(echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||')" >> $GITHUB_ENV
          cat << EOF > auto.tf
          terraform {
            backend "s3" {}
          }
          variable "git" {}
          EOF
      - name: init
        run: terraform init -backend-config key=${TF_VAR_git} -backend-config bucket=${TF_STATE_BUCKET}
      - name: validate
        run: terraform validate
      - name: check
        run: terraform plan -detailed-exitcode